### ISSUE TITLE
Blue Ice not working?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [UtechtDustin/Builder-s-Wand#30]
I can't place Blue Ice with the wand. I am using Spigot 1.13.2 (re-built yesterday). Netherrack for example is working

**Comment by UtechtDustin** [comment]
Would fix ist, but currently mojang is not fixing a bug whit the minecraft launcher and linux.
So i cant start minecraft.

**Comment by ThexXTURBOXx** [comment]
Okay, thank you!
As a tip: I am using MultiMC and it works great on Linux. Maybe you want to switch to it, too (it has so many new features) :)

**Comment by UtechtDustin** [comment]
I also tried other launchers, but its an issue of the auth server...
```
An unknown error occurred when trying to communicate with the authentication server: Error downloading https://authserver.mojang.com/authenticate - server replied: Forbidden
```
The Bug is already reported to mojang.

**Comment by ThexXTURBOXx** [comment]
Ah okay.
And I just noticed, there are many other Blocks, which don't work, too. I tried Brown stained Glass right now and it doesn't work as well. Weird

**Comment by unnown** [comment]
any block with item data other then 0 doesn't work, unless op'ed ofcourse
seems it's checking item durability instead of the also depricated item data

**Comment by ThexXTURBOXx** [comment]
Okay, I already thought, that something like that is the problem. 1.13 did change a lot of things lol

**Comment by matthewes1** [comment]
Wood planks also don't work

**Comment by ThexXTURBOXx** [comment]
Hey, any progress here and maybe a 1.14 build in sight? 
Btw: There is a workaround for linux systems running minecraft: https://github.com/MultiMC/MultiMC5/issues/2614, I helped there

**Comment by UtechtDustin** [comment]
@ThexXTURBOXx 
Thanks for the informations i will try to compile multimc myself.

**Comment by UtechtDustin** [comment]
@ThexXTURBOXx 
Its doesnt fixed the issue, its seems that i have also a other issue...
So i have to wait for mojang (https://bugs.mojang.com/projects/MCL/issues/MCL-10038?filter=allopenissues)

**Comment by ThexXTURBOXx** [comment]
That's a bummer... I'm sorry then :/

**Comment by ThexXTURBOXx** [comment]
How can you build the plugin? I fixed support for 1.14 and maybe the metadata bug, but I can't build the plugin, because there are many dependencies missing. I think, the pom.xml is very out of date?

**Comment by UtechtDustin** [comment]
Just add the dependencies, some of them cant be added via pom.

**Comment by ThexXTURBOXx** [comment]
Okay

**Comment by matthewes1** [comment]
@ThexXTURBOXx When you get it compiled can yous end me a copy or post the updates on a branch?

**Comment by ThexXTURBOXx** [comment]
Yes, I will do that!

**Comment by UtechtDustin** [comment]
You can send me a PullRequest, i will check and accept it...
If can start Minecraft someday... (f***ing Mojang)...

**Comment by matthewes1** [comment]
I hope they fix that issue man. With how big their platforms are you'd figure they'd get linux working asap
