### ISSUE TITLE
inventory bug

### ISSUE THREAD

**Issue by Gian2111** [UtechtDustin/Builder-s-Wand#34]
Hi, I don't know if it's the right place to report an error, or I'm doing something wrong.

The plugin works perfectly except inventory, does weird things and won't let me move items.

It only happens with the fire and the diamond bar. Try to change the recipe, but it doesn't seem to work

I leave a little video to see what I mean:

https://gyazo.com/ff9d56afca6987b3cd0768d1d390f041

Thank you for its tempo, the truth that the plugin is very good, but it hurts this little problem that is quite annoying, already try to disable several options, but there is no effect

I also tried permissive, but there doesn't seem to be any change.

Excuse my English

**Comment by UtechtDustin** [comment]
fixed
