### ISSUE TITLE
Wand doesn't work underwater

### ISSUE THREAD

**Issue by SkillzGamingYT** [UtechtDustin/Builder-s-Wand#37]
The wand doesn't work underwater

![2019-07-13_18 55 40](https://user-images.githubusercontent.com/26197169/61168300-f75d9800-a59f-11e9-93f7-ecdef9ab9a97.png)

**Comment by UtechtDustin** [comment]
Currently not possible to implement cause buggy functions of spigot.
I will implement it as soon as possible.
