### ISSUE TITLE
[SUGGESTION] Wand should consider dirt as grass block.

### ISSUE THREAD

**Issue by SkillzGamingYT** [UtechtDustin/Builder-s-Wand#38]
Wand doesn't reconsider dirt block as grass block making building dirt platform harder.

![2019-07-13_18 21 26](https://user-images.githubusercontent.com/26197169/61169697-ac01b480-a5b4-11e9-9f52-b8e6c442c493.png)

**Comment by UtechtDustin** [comment]
Sorry but i think that is not a good idea.   
If someone will build grass he will maybe build dirt instead.

If you want to build a dirt platform, just build a row of dirt first then you can easy use the wand.
