### ISSUE TITLE
Put block on hat slot

### ISSUE THREAD

**Issue by HiImSunny** [UtechtDustin/Builder-s-Wand#50]
When put block on hat and use builderwands, i can use that block like unlimited

**Comment by UtechtDustin** [comment]
I will check that, but there is only one Block (pumpkin) which can be used as hat or ?

**Comment by HiImSunny** [comment]
i dont know is this error can use without essentials. I use essentials so i can put any block in helmet slot

**Comment by UtechtDustin** [comment]
Should be fixed in the newest version @HiImSunny.
