### ISSUE TITLE
shulker boxes get wiped

### ISSUE THREAD

**Issue by AmyMialee** [UtechtDustin/Builder-s-Wand#52]
as per title

**Comment by UtechtDustin** [comment]
What do you mean with "get wiped". ?

**Comment by AmyMialee** [comment]
contents deleted

personally I'd just blacklist shulker boxes since they're the only tile
entity you can carry in survival

**Comment by UtechtDustin** [comment]
Okay, it seems you found a solution.

**Comment by AmyMialee** [comment]
is there a blacklist config? if so that'd do.

you should probably make it blacklist them by default.

**Comment by UtechtDustin** [comment]
Yea there is a blacklist config, checkout the plugin page.
You dont explained what do you mean with `get wiped` ?

**Comment by AmyMialee** [comment]
I don't see any blacklist config on the page or in the config folder.

Also like I said, the items in the shulker box get cleared.

**Comment by UtechtDustin** [comment]
> I don't see any blacklist config on the page or in the config folder.
Its on the "files" section with the example config...

> Also like I said, the items in the shulker box get cleared.
You didnt wrote that, but now i know what you mean ;)
