### ISSUE TITLE
It gives me error and it doesnt work.

### ISSUE THREAD

**Issue by DarknightHD** [UtechtDustin/Builder-s-Wand#56]
Hello good day!
I'm having a problem about builderswand, it seems i got error and also it didnt work.
heres the screenshot
https://i.imgur.com/ZIXy4SM.png

**Comment by johnneijzen** [comment]
okay that was oversight by plugin dev apparently any normal block would work but fences there is need null check or size check in place because it will return 1 instead of 2 @UtechtDustin 
https://www.spigotmc.org/threads/getting-the-blockface-of-a-targeted-block.319181/

**Comment by johnneijzen** [comment]
i just did double check if really possible to get null
![image](https://user-images.githubusercontent.com/1343960/116778712-2eb77480-aaa6-11eb-828f-eea3e4b9c3f5.png)
