### ISSUE TITLE
Players Can Use Wand in Other Player Claims | GriefPrevention

### ISSUE THREAD

**Issue by iLuckyx** [UtechtDustin/Builder-s-Wand#57]
Issue: Players can use the wand in other peoples claim even if they are not trusted
Replicate:
- Use wand in a claim land you don't own

Running, latest version of paper, GriefPrevention and BuilderWand

**Comment by UtechtDustin** [comment]
GriefPrevention should work fine, maybe they changed the api.
Do you get any errors in the console ?

**Comment by iLuckyx** [comment]
No errors within console that I see. I noticed I was running 2.18.0 for some reason, so I'm updating a rerunning my tests and will let you know.

**Comment by iLuckyx** [comment]
Disregard. No issue. When opped you get the permission to buildersWand.bypass which prevents that. Misunderstanding.

**Comment by Drakusiek** [comment]
GP have permission called griefpreventation.bypass
if that person can bypass clans.
check if default have it!
