### ISSUE TITLE
Claimchunk support

### ISSUE THREAD

**Issue by testablebox048** [UtechtDustin/Builder-s-Wand#62]
Hello I was wondering if you could make more support for claim plugins? I say that due to the fact that most server owners have to use your only supported claim protection. It stops a lot of people from adding it because of this. I can't add it due to the fact that https://www.spigotmc.org/resources/claimchunk.44458/ Is my claim protection.

Ps this is a great plugin!

**Comment by UtechtDustin** [comment]
Sure! If i have time i could add it, but i can't find a api for that plugin.

**Comment by testablebox048** [comment]
I would ask the developer for it?

**Comment by UtechtDustin** [comment]
Sure :-)

**Comment by UtechtDustin** [comment]
@testablebox048 do you have new information about the api ?

**Comment by UtechtDustin** [comment]
I will close this issue, because i got no response from you.
