### ISSUE TITLE
Error spam

### ISSUE THREAD

**Issue by cloakfox** [UtechtDustin/Builder-s-Wand#71]
https://gist.github.com/cloakfox/eb0382c9f51ece3e727a623e5dc56449

**Comment by UtechtDustin** [comment]
Please show me your config file of the wands.

**Comment by cloakfox** [comment]
config.yml: https://gist.github.com/cloakfox/19d276fcbdf1663916055bdbbb9b1684

wands.yml: https://gist.github.com/cloakfox/81d5e9a425bed8aff806feb0cfb8c559

**Comment by cloakfox** [comment]
Bump https://gist.github.com/cloakfox/ba6a90314c6a2b8b036331f1beb22a65

**Comment by UtechtDustin** [comment]
Strange... do you changed the format of the durability in the config ?

**Comment by cloakfox** [comment]
> Strange... do you changed the format of the durability in the config ?

I send my config & wands ymls 2 weeks ago, havent touched them since

**Comment by UtechtDustin** [comment]
Do you get the error on every wand or maybe just on a wand which was created a longer time ago ?
Could you please test it with a blank server, with the default configs ?

I can't reproduce the error.

**Comment by cloakfox** [comment]
> 

Idk, im just seeing error spam in our console and reported it here, was hoping the author of the plugin knows whats going on.

**Comment by UtechtDustin** [comment]
Without more information i can't help, because i can't reproduce the issue.
You can check if get the error with the default config, if you don't get the error you know the issue is a change on you're side.

**Comment by cloakfox** [comment]
> Without more information i can't help, because i can't reproduce the issue. You can check if get the error with the default config, if you don't get the error you know the issue is a change on you're side.

You've seen the configs I use currently, I dont believe that there is a typo in those.

**Comment by UtechtDustin** [comment]
As i said, i can't reproduce the issue which means i have no chance to debug it further.
The issue is caused because the durability of wand can't be parsed.

**Comment by cloakfox** [comment]
Strange that it cannot be parsed, we have 2 types of wands in the game, i finite ones and one with like 50 durability

**Comment by UtechtDustin** [comment]
Wait.. i rechecked your wands config and saw this `&eDurability&f: Infinite`.
That can't be parsed.. if you wan't a wand without durability just set `enabled` to `false`.

**Comment by cloakfox** [comment]
> Wait.. i rechecked your wands config and saw this `&eDurability&f: Infinite`. That can't be parsed.. if you wan't a wand without durability just set `enabled` to `false`.

Ahh I see, thanks for helping out

**Comment by cloakfox** [comment]
> Wait.. i rechecked your wands config and saw this `&eDurability&f: Infinite`. That can't be parsed.. if you wan't a wand without durability just set `enabled` to `false`.

Would changing this, break old "infinite" wands?

**Comment by UtechtDustin** [comment]
I guess the wand's should still work, but the lore is broken (shows the durability text).
But im not quite sure right now, never tried it.

**Comment by cloakfox** [comment]
> I guess the wand's should still work, but the lore is broken (shows the durability text). But im not quite sure right now, never tried it.

Hmn still getting quite a bit of spam after changing the config value and reloading the plugin with /bw reload
https://gist.github.com/cloakfox/0747f64f94398c14fcccd5edaf9e9cfa

**Comment by UtechtDustin** [comment]
With the old Wands or with a new one ?

**Comment by UtechtDustin** [comment]
duplicate of #74
