### ISSUE TITLE
Copy flower

### ISSUE THREAD

**Issue by YunDouYue** [UtechtDustin/Builder-s-Wand#72]
The premise is that there are four flowers on the ground
The magic wand using this plugin( It needs to be pressed all the time )
You can copy
Potatoes and carrots can also be copied..
Please fix it as soon as possible thanks

**Comment by UtechtDustin** [comment]
Could you post a screenshot of the setup ?
I can't reproduce it.

**Comment by UtechtDustin** [comment]
As i got now news from you, i will close this issue.
