### ISSUE TITLE
Error Sometimes Spams Console

### ISSUE THREAD

**Issue by Twocoolguy** [UtechtDustin/Builder-s-Wand#73]
Every now and then I start having an error get spammed in the console. I haven't found anything so I can reproduce this but I definitely keep getting this error spammed for some reason.
Error: https://pastebin.com/n8aR4cLw
config.yml: https://pastebin.com/5bST0Ti4
wands.yml: https://pastebin.com/pa1XPaEa

Hope this can get resolved, thanks!

**Comment by UtechtDustin** [comment]
Should be fixed in the version `2.22.0`, will be released in a few minutes.
