### ISSUE TITLE
TPS and MSTP lag

### ISSUE THREAD

**Issue by MoistMelonGaming** [UtechtDustin/Builder-s-Wand#76]
Hello,

I have noticed recently when myself or a player has a wand out and has it hover over a block my servers TPS and MSTP go haywire. I have made no real changes to anything in the config. I am running the latest PurPur jar. 

I have also tried removing the particles to see if that is causing the issue but the server still has TPS drops when simply hovering the wand over the area to be worked on.

I do not recall having this issue in 1.17.1 just in 1.18.1,

If you need anymore information please just let me know what you need.

**Comment by UtechtDustin** [comment]
I don't think i changed revant stuff which could cause a difference between 1.17 and 1.18.
I'm currently rewrite the whole plugin and will improve the performance, the current version is my first plugin ever.
So its not optimized (yet).
